### ISSUE TITLE
Failed to load with frameworkPath

### ISSUE THREAD

**Issue by sylouuu** [mattfritz/protractor-cucumber-framework#12]
Hi,

I'm trying to use cucumber with basic tests found in cucumberjs readme.

```
cucumberjs --version
0.9.2

protractor --version
Version 3.0.0
```

```js
/* protractor.conf.js */
exports.config = {
    rootElement: '[ng-app]',

    seleniumServerJar: 'node_modules/selenium-server/lib/runner/selenium-server-standalone-2.48.2.jar',

    specs: [
        'tests/e2e/myfeature.feature'
    ],

    getPageTimeout: 100000,

    onPrepare: function() {
        global.__base = __dirname + '/';
    },

    capabilities: {
        browserName: 'chrome',
        version: '',
        platform: 'ANY',
        idleTimeout: 90
    },

    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),

    cucumberOpts: {
        require: [
            'tests/e2e/steps/mystep.js',
        ],
        format: 'pretty', // or summary
        keepAlive: false
    },

    onCleanUp: function() {}

};
```

**myfeature.feature**:

```
Feature: Example feature
    As a user of cucumber.js
    I want to have documentation on cucumber
    So that I can concentrate on building awesome applications

    Scenario: Reading documentation
        Given I am on the Cucumber.js GitHub repository
        When I go to the README file
        Then I should see "Usage" as the page title
```

**mystep.js**:

```js
module.exports = function () {
    this.World = require(__base +'tests/e2e/support/world').World;

    this.Given(/^I am on the Cucumber.js GitHub repository$/, function (callback) {
        // Express the regexp above with the code you wish you had.
        // `this` is set to a World instance.
        // i.e. you may use this.browser to execute the step:

        console.log(this);

        this.visit('https://github.com/cucumber/cucumber-js', callback);

        // The callback is passed to visit() so that when the job's finished, the next step can
        // be executed by Cucumber.
    });

    this.When(/^I go to the README file$/, function (callback) {
        // Express the regexp above with the code you wish you had. Call callback() at the end
        // of the step, or callback.pending() if the step is not yet implemented:

        callback.pending();
    });

    this.Then(/^I should see "(.*)" as the page title$/, function (title, callback) {
        // matching groups are passed as parameters to the step definition

        var pageTitle = this.browser.text('title');
        if (title === pageTitle) {
            callback();
        } else {
            callback(new Error("Expected to be on page with title " + title));
        }
    });
};
```

```
protractor protractor.conf.js --baseUrl="my-url-website"
```

Here is my output:

```
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.168.82:55494/wd/hub
[launcher] Error: TypeError: Path must be a string. Received false
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:424:5)
    at Object.realpathSync (fs.js:1380:18)
    at Object.expandPathWithRegexp (/Users/syl/Sites/pro/back-office-edito-web/node_modules/cucumber/lib/cucumber/cli/path_expander.js:23:23)
    at /Users/syl/Sites/pro/back-office-edito-web/node_modules/cucumber/lib/cucumber/cli/path_expander.js:9:39
    at Array.forEach (native)
    at Object.expandPathsWithRegexp (/Users/syl/Sites/pro/back-office-edito-web/node_modules/cucumber/lib/cucumber/cli/path_expander.js:8:11)
    at Object.expandPaths (/Users/syl/Sites/pro/back-office-edito-web/node_modules/cucumber/lib/cucumber/cli/feature_path_expander.js:6:38)
    at getFeaturePaths (/Users/syl/Sites/pro/back-office-edito-web/node_modules/cucumber/lib/cucumber/cli/configuration.js:34:45)
    at Object.getFeatureSources (/Users/syl/Sites/pro/back-office-edito-web/node_modules/cucumber/lib/cucumber/cli/configuration.js:110:26)
[launcher] Process exited with error code 100
```

I commented the feature file but nothing. Have you an idea?

Bests :)

**Comment by darrinholst** [comment]
It doesn't currently support `false` options so removing `keepAlive: false` should get you going

**Comment by sylouuu** [comment]
Allright thx!
