### ISSUE TITLE
cucumberOpts ES6 compiler 

### ISSUE THREAD

**Issue by artemjackson** [mattfritz/protractor-cucumber-framework#15]
Seems that cucumber compiler does not work with `es6` and `babel-core/register`
```
// protractor.conf.js
...
framework: "custom",

frameworkPath: require.resolve("protractor-cucumber-framework"),

cucumberOpts: {
    compiler: "es6:babel-core/register",
    require: "features/step_definitions/**/*.es6"
}
...
```
Error occured:
`Error: SyntaxError: Unexpected token import`

Any ideas?
Tried with
```
"babel-core": "6.3.21",
"cucumber": "0.9.2",    
"protractor": "3.0.0",
"protractor-cucumber-framework": "0.3.2"
```

**Comment by darrinholst** [comment]
This is probably more of a cucumber usage question. If you run protractor with debugging it will show the actual cucumber command that was used...`DEBUG=protractor-cucumber-framework protractor protractor.conf.js`. All this library does is build up a cucumber command and collect the test results.

**Comment by artemjackson** [comment]
Yep, I can confirm that options are sent correctly 
it's probably cucumber usaqe issue

**Comment by kosalanuwan** [comment]
Does it work for Babel 7+? I tried this with `cucumberOpts` `compiler: ['@babel/register']` but doesn't seems to work. Keeps complaining about `import` statements.
```bash
import { browser } from 'protractor';
       ^
SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/kp/hello-world/e2e/pages/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at supportCodePaths.forEach.codePath (/Users/kp/hello-world/node_modules/cucumber/lib/cli/index.js:142:42)
[14:15:31] E/launcher - Process exited with error code 100
```
What's in the code:
```js
// e2e/pages/nagivator.js
import { browser } from 'protractor';
export async function gotoGitHub () { return await browser.get(''); }
```

What's included in `package.json`:
```json
"devDependencies": {
    "@babel/cli": "7.5.5",
    "@babel/core": "7.5.5",
    "@babel/preset-env": "7.5.5",
    "@babel/register": "7.5.5",
    "babel-core": "6.26.3",
    "chai": "4.2.0",
    "chai-as-promised": "7.1.1",
    "core-js": "3.2.1",
    "cucumber": "5.1.0",
    "eslint": "6.2.2",
    "mkdirp": "0.5.1",
    "protractor": "5.4.2",
    "protractor-cucumber-framework": "6.1.3",
    "rimraf": "3.0.0"
},
"scripts": {
    "test:fast": "protractor config/config.local.js"
}
```
What's included in `config/config.local.js`:
> Doesn't work w/ or w/out the `compiler` option.
```js
{
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    cucumberOpts: {
        requireModule: ['@babel/core', '@babel/preset-env', '@babel/register'],
        require: ['../e2e/**/*.js'],
        format: 'json:./.temp/results.json',
        tags: [],
        strict: true,
        dryRun: false,
        // compiler: ['js:@babel/register'],
    },
    onPrepare: function () {},
    onCleanUp: function () {},
    onComplete: function () {},
}
```
What's included in `.babelrc`:
```json
{
    "presets": ["@babel/preset-env"]
}
```
What's included in `babel.config.js`:
```js
{
    presets: [
        ['@babel/preset-env', {
            targets: { node: 'current' },
            useBuiltIns: 'entry',
            corejs: { version: 3 },
        }]
    ]
}
```
