### ISSUE TITLE
Stack-chain error causes tests to suddenly timeout

### ISSUE THREAD

**Issue by Maria-Gutierrez** [mattfritz/protractor-cucumber-framework#4]
Whenever I try to run any protractor-cucumber test after upgrading Protactor to the latest verion (3.0) and adding on the configuration file:
  framework: 'custom',
  frameworkPath: '../e2e/node_modules/protractor-cucumber-framework',

I'm getting the following error:

 Scenario: Viewing library that contains magazines and books
    Given I am logged in as "user@se.co.uk"
      Error: Step timed out after 5000 milliseconds
          at Timer.listOnTimeout (timers.js:92:15)

Scenario: Clicking on magazine on library
    Given I am logged in as "user@se.co.uk"
      TypeError: Cannot define property:callSite, object is not extensible.
          at Function.defineProperty (native)

Stack trace follows:

/Users/maria/automation/automation/test/e2e/node_modules/cucumber/node_modules/stack-chain/stack-chain.js:195
    Object.defineProperty(this, 'callSite', {
           ^
TypeError: Cannot define property:callSite, object is not extensible.
    at Function.defineProperty (native)
    at [object Object].Object.defineProperty.set (/Users/maria/automation/automation/test/e2e/node_modules/cucumber/node_modules/stack-chain/stack-chain.js:195:12)
    at Function.prepareStackTrace (/Users/maria/automation/automation/test/e2e/node_modules/cucumber/node_modules/stack-chain/stack-chain.js:141:20)
    at [object Object].promise.Promise.goog.defineClass.resolve_ (/Users/maria/automation/automation/test/e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1128:38)
    at eval (/Users/maria/automation/automation/test/e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1059:14)
    at [object Object].reject (/Users/maria/automation/automation/test/e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1400:7)
    at eval (/Users/maria/automation/automation/test/e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2708:36)
    at Array.forEach (native)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.interrupts_.forEach [as abort_] (/Users/maria/automation/automation/test/e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2708:19)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.processUnhandledRejections_ (/Users/maria/automation/automation/test/e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2808:12)
[launcher] Process exited with error code 1

Seems like a potential problem with stack-chain, a dependency of cucumber. I actually found [this bug report](https://github.com/medikoo/error-create/issues/1) on their repo, which is still to be diagnosed.

Any idea what could be happening?

Thanks!

**Comment by mattfritz** [comment]
If I had a guess, either `selenium-webdriver` or `cucumber-js` is feeding `stack-chain` an error it can't properly handle. I don't think it has anything to do with breaking out the Cucumber framework.

This issue https://github.com/AndreasMadsen/stack-chain/issues/9 looks like a similar if not identical problem. I'm going to close this issue for now since it looks like a framework or driver issue, but feel free to post here again if you find more info.

Side note, the `frameworkPath` option gets resolved and required. So if you want to change the relative path to
```js
frameworkPath: 'protractor-cucumber-framework'
```
it should work the same. Thanks!

**Comment by Maria-Gutierrez** [comment]
Thanks for the quick reply!
Looks like the problem (or part of it)  was handled buy a PR on stack-chain:
https://github.com/AndreasMadsen/stack-chain/pull/10
