### ISSUE TITLE
 Angular 2 "Failed Loading Configuration File" Error

### ISSUE THREAD

**Issue by JimTheMan** [mattfritz/protractor-cucumber-framework#49]
Hi, I was able to get this working for AngularJS projects, but I'm getting a strange error when trying to use it with Angular 2. Here's my protractor.conf.js:

This is the error that is displayed: 
```
[10:40:47] E/configParser - error code: 105
[10:40:47] E/configParser - description: failed loading configuration file config/acceptance-protractor.conf.js

/Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/protractor/built/configParser.js:130
            throw new exitCodes_1.ConfigError(logger, 'failed loading configuration file ' + filename);
            ^
Error
    at ConfigError.ProtractorError (/Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/protractor/built/exitCodes.js:10:22)
    at new ConfigError (/Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/protractor/built/exitCodes.js:26:16)
    at ConfigParser.addFileConfig (/Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/protractor/built/configParser.js:130:19)
    at Object.initFn [as init] (/Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/protractor/built/launcher.js:94:22)
    at Object.<anonymous> (/Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/protractor/built/cli.js:130:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

![angular-2-screencast-example_ _-bash_ _153x21_and_angular-2-screencast-example_-____git-projects_angular-2-screencast-example__and_footer_step_js_-_ng-nj_org_-____git-projects_ng-nj_org_](https://cloud.githubusercontent.com/assets/5354163/17060763/79c3d1d8-4ff9-11e6-8165-725fb901a3ed.png)

Here's my protractor.conf file:

// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/docs/referenceConf.js

/*global jasmine */
// var SpecReporter = require('jasmine-spec-reporter');

exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    

> '../src/**/*.feature',
>     '../src/**/*.step.js

  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'custom',

  // path relative to the current config file
  frameworkPath: require.resolve('protractor-cucumber-framework'),
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  useAllAngular2AppRoots: true,
  beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e'
    });
  },
  onPrepare: function() {
    // jasmine.getEnv().addReporter(new SpecReporter());
  }
};

And I'm runnign it with this command:
```
./node_modules/protractor/bin/protractor config/acceptance-protractor.conf.js 
```

**Comment by AlexandrosD** [comment]
This is caused by https://github.com/angular/protractor/issues/3301

A `require

**Comment by JimTheMan** [comment]
Hi,  Thanks @AlexandrosD !

But the error is still happening after npm install...

**Comment by JimTheMan** [comment]
ok. I commented out all of the require's, but I'm getting a new error message.

My new protractor.conf:

```
// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/docs/referenceConf.js

/*global jasmine */
// var SpecReporter = require('jasmine-spec-reporter');

exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    '../src/**/*.feature',
    '../src/**/*.step.js'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'custom',

  // path relative to the current config file
  // frameworkPath: require.resolve('protractor-cucumber-framework'),
  frameworkPath: ('../node_modules/protractor-cucumber-framework'),
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  useAllAngular2AppRoots: true,
  beforeLaunch: function() {
    // require('ts-node').register({
    //   project: 'e2e'
    // });
  },
  onPrepare: function() {
    // jasmine.getEnv().addReporter(new SpecReporter());
  }
};
```



Error:

[11:45:23] I/direct - Using ChromeDriver directly...
[11:45:23] I/launcher - Running 1 instances of WebDriver
[11:45:38] E/launcher - Error: CompositeParserException: Parser errors:
(2:3): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Feature Something'
(3:5): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'As someone'
(4:5): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'I want something'
(5:5): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'in order to do something'
(8:5): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Scenario: some scenario'
(9:7): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Given some thing'
(10:7): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'When some other thing'
(11:7): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Then a differen thing'
path: /Users/jim/Git-Projects/Angular-2-Screencast-Example/src/app/some.feature
    at Function.Errors.CompositeParserException.create (/Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/gherkin/lib/gherkin/errors.js:27:13)
    at Parser.parse (/Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/gherkin/lib/gherkin/parser.js:79:45)
    at /Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/cucumber/lib/cucumber/parser.js:18:36
    at Array.forEach (native)
    at Object.parse (/Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/cucumber/lib/cucumber/parser.js:12:22)
    at Object.getFeatures (/Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/cucumber/lib/cucumber/runtime.js:38:35)
    at Object.start (/Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/cucumber/lib/cucumber/runtime.js:11:27)
    at Object.run (/Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/cucumber/lib/cucumber/cli.js:58:15)
    at /Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/protractor-cucumber-framework/index.js:31:34
    at Function.promise (/Users/jim/Git-Projects/Angular-2-Screencast-Example/node_modules/q/q.js:682:9)
[11:45:38] E/launcher - Process exited with error code 100

![angular-2-screencast-example_ _-bash_ _157x28](https://cloud.githubusercontent.com/assets/5354163/17062888/c6df2acc-5002-11e6-8cba-55ae861ef065.png)


Is this just telling me that it kind find the step definition files, or it there something else wrong here? thanks.

**Comment by calendir** [comment]
Could you share the .feature file you're trying to run? Also, step definitions shouldn't be under `specs` but rather under `cucumberOpts.require`.

Try this (I've skipped all unnecessary/commented lines): 
```
exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    '../src/**/*.feature'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  cucumberOpts: {
    require: [
      '../src/**/*.step.js'
    ]
  }
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'custom',

  frameworkPath: ('../node_modules/protractor-cucumber-framework'),
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  useAllAngular2AppRoots: true
};
```

**Comment by NewWorldAnks** [comment]
I am also facing same issue. Is there any solution for this?
NPM version: 3.10.3
Protractor version: 4.0.4
Error:
Checking out Revision ac4c9ddf80c2a9e0b6190a1be9c4196716916170 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ac4c9ddf80c2a9e0b6190a1be9c4196716916170
 > git rev-list 6a3c1267f35fa936a546360899d0bd75ca349e48 # timeout=10
[Demo] $ /bin/sh -xe /var/folders/v7/0h9sdzsd0pg368s4w2dp6pvscw2175/T/hudson7947513718618591968.sh
+ npm install
+ ./node_modules/.bin/gulp test --site sitename --suite smoke
[13:07:10] Using gulpfile ~/.jenkins/workspace/Demo/gulpfile.js
[13:07:10] Starting 'test'...
[13:07:10] Testing sites/sitename
[13:07:10] E/configParser - error code: 105
[13:07:10] E/configParser - description: failed loading configuration file ./sites/sitename/protractor.conf.js

/Users/username/.jenkins/workspace/Demo/node_modules/protractor/built/configParser.js:130
            throw new exitCodes_1.ConfigError(logger, 'failed loading configuration file ' + filename);
            ^
Error
    at ConfigError.ProtractorError (/Users/username/.jenkins/workspace/Demo/node_modules/protractor/built/exitCodes.js:10:22)
    at new ConfigError (/Users/username/.jenkins/workspace/Demo/node_modules/protractor/built/exitCodes.js:26:16)
    at ConfigParser.addFileConfig (/Users/username/.jenkins/workspace/Demo/node_modules/protractor/built/configParser.js:130:19)
    at Object.initFn [as init] (/Users/username/.jenkins/workspace/Demo/node_modules/protractor/built/launcher.js:94:22)
    at Object.<anonymous> (/Users/username/.jenkins/workspace/Demo/node_modules/protractor/built/cli.js:130:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by calendir** [comment]
Share your config file, please.

**Comment by saicharanmallampalli** [comment]
Hi,
I'm new to protractor, i'm trying to run the protractor scripts through Eclipse IDE. I'm seeing the same issue.  

[11:20:09] E/configParser - [SyntaxError: Unexpected token class]
[11:20:09] E/configParser - Error code: 105
[11:20:09] E/configParser - Error message: failed loading configuration file E:\Protractor\Sample-Protractor\conf.js
[11:20:09] E/configParser - SyntaxError: Unexpected token class
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at ConfigParser.addFileConfig (E:\Protractor\Sample-Protractor\node_modules\protractor\built\configParser.js:128:26)
    at Object.initFn [as init] (E:\Protractor\Sample-Protractor\node_modules\protractor\built\launcher.js:97:22)
    at Object.<anonymous> (E:\Protractor\Sample-Protractor\node_modules\protractor\built\cli.js:112:10)


Below is my conf.js and to-do.js file : 

conf.js class
exports.config = {
//seleniumAddress: 'http://localhost:4444/wd/hub',
directConnect: true,
specs: ['to-do.js']
};

describe('angularjs homepage todo list', function() {
it('should add a todo', function() {
browser.get('https://angularjs.org');

element(by.model('todoList.todoText')).sendKeys('write first protractor test');
element(by.css('[value="add"]')).click();

var todoList = element.all(by.repeater('todo in todoList.todos'));
expect(todoList.count()).toEqual(3);
expect(todoList.get(2).getText()).toEqual('write first protractor test');

// You wrote your first test, cross it off the list
todoList.get(2).element(by.css('input')).click();
var completedAmount = element.all(by.css('.done-true'));
expect(completedAmount.count()).toEqual(2);
});
});

**Comment by nits34** [comment]
Hi I am getting below error while running the configuration file

I have done the below steps
1. npm install --save-dev webdriver-manager protractor cucumber protractor-cucumber-framework

D:\cucumbersample\features>protractor test.js
[16:42:56] E/configParser - Error code: 105
[16:42:56] E/configParser - Error message: failed loading configuration file tes
t.js
[16:42:56] E/configParser - Error: Cannot find module 'protractor-cucumber-frame
work'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.<anonymous> (D:\cucumbersample\features\test.js:15:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

so i tried to install cucumber again
npm install cucumber
still facing the issue.
Could you please suggest what is the issue and how to resolve it

**Comment by nits34** [comment]
here is my configuration file
exports.config = {

  seleniumAddress: 'http://localhost:4444/wd/hub', // This is targetting your local running instance of the selenium webdriver

  specs: [
    './button.feature'
  ],

  capabilities: {
    browserName: 'chrome' // You can use any browser you want. On a CI environment you're going to want to use PhantomJS
  },

  framework: 'custom', //We need this line to use the cucumber framework

  frameworkPath: require.resolve('protractor-cucumber-framework'), // Here it is

  cucumberOpts: {
    format:  'pretty',
    require: './step_definitions/*.js', // This is where we'll be writing our actual tests
  },

  params: {
    env: {
      hostname: 'file:///D:/cucumbersample/home.html' // Whatever the address of your app is
    }
  }

};
