### ISSUE TITLE
"Reduce of empty array with no initial value" Error message when executing protractor

### ISSUE THREAD

**Issue by Maria-Gutierrez** [mattfritz/protractor-cucumber-framework#6]
Hi again!

I'm trying to install protractor-cucumber-framework again, but when trying to execute a test, I'm getting the following error:
````
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://10.152.250.231:56864/wd/hub
[launcher] Error: TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at /Users/maria/automation/automation/test/e2e/node_modules/protractor-cucumber-framework/index.js:36:12
    at Array.forEach (native)
    at Object.exports.run (/Users/maria/automation/automation/test/e2e/node_modules/protractor-cucumber-framework/index.js:26:45)
    at /Users/maria/automation/automation/test/e2e/node_modules/protractor/lib/runner.js:337:35
    at _fulfilled (/Users/maria/automation/automation/test/e2e/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/Users/maria/automation/automation/test/e2e/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/Users/maria/automation/automation/test/e2e/node_modules/protractor/node_modules/q/q.js:759:13)
    at /Users/maria/automation/automation/test/e2e/node_modules/protractor/node_modules/q/q.js:525:49
    at flush (/Users/maria/automation/automation/test/e2e/node_modules/protractor/node_modules/q/q.js:108:17)
[launcher] Process exited with error code 100
````
Anything I'm missing out during the install?
Thanks!

**Comment by mattfritz** [comment]
Good catch! Fixed in https://github.com/mattfritz/protractor-cucumber-framework/commit/bb7862ff3a9634b5a89833b51a61bc00216966ed . Let me know if you see anything else.
