### ISSUE TITLE
Error: TypeError: tag.replace is not a function

### ISSUE THREAD

**Issue by SGoldenGraham** [mattfritz/protractor-cucumber-framework#72]
I am using the fork 'darrinholst/protractor-cucumber-framework#cucumber-2' but I can't find an issue section on that page. When I try and run protractor I get the following error:

 E/launcher - Error: TypeError: tag.replace is not a function
    at C:\gitlab\ma\node_modules\protractor-cucumber-framework\index.js:95:18
    at Array.map (native)
    at convertTagsToCliValues (C:\gitlab\ma\node_modules\protractor-cucumber-framework\index.js:94:37)
    at convertOptionValueToCliValues (C:\gitlab\ma\node_modules\protractor-cucumber-framework\index.js:113:14)
    at convertOptionsToCliArguments (C:\gitlab\ma\node_modules\protractor-cucumber-framework\index.js:61:31)
    at C:\gitlab\ma\node_modules\protractor-cucumber-framework\index.js:25:26
    at Function.promise (C:\gitlab\ma\node_modules\q\q.js:682:9)
    at C:\gitlab\ma\node_modules\protractor-cucumber-framework\index.js:24:14
    at _fulfilled (C:\gitlab\ma\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\gitlab\ma\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\gitlab\ma\node_modules\q\q.js:796:13)
    at C:\gitlab\ma\node_modules\q\q.js:556:49
    at runSingle (C:\gitlab\ma\node_modules\q\q.js:137:13)
    at flush (C:\gitlab\ma\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[15:09:23] E/launcher - Process exited with error code 100

**Comment by SGoldenGraham** [comment]
My protractor.conf.js had the following settings:

  cucumberOpts: {
    require: ['./e2e/features/steps/*.steps.ts'],
    tags: false,
    format: 'pretty',
    profile: false,
    'no-source': true
  }

I had to remove the 'tags' option and it worked correctly. Having it set to either false or true caused an error.

**Comment by darrinholst** [comment]
Good catch. Since cucumber 2 changed it's [tag format](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/index.js#L93) I tried to be "helpful" and do the conversion [automatically](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/blob/master/index.js#L93). Need to check that it's a string before being so helpful.

**Comment by Simon-Graham-ila** [comment]
Cheers for the fast response Darrin! I'll give it a whirl.
